name: Bandit Security Scan

on:
  push:
    #paths:
    #  - '**.py'

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.11"  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install -r requirements.txt
      - name: Run Bandit
        run: |
          bandit -r .